
source 'https://github.com/Cocoapods/Specs.git'

platform :ios, '8.0'

target 'coderConf' do
	react_native_path = "../node_modules/react-native"
	pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
	pod 'React', :path => react_native_path


	pod 'GoogleMaps'

end